remote_theme: "mmistakes/minimal-mistakes"

# Site Settings
locale                   : "en-US"
title                    : "On The Line: Jekyll book with remote theme"
title_separator          : "-"
name                     : &name "by Jack Dougherty and contributors" # &name is a YAML anchor which can be *referenced later
description              : &description "A flexible Jekyll theme for your blog or site with a minimalist aesthetic."
url                      : "https://ontheline.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/otl-book" # the subpath of your site, e.g. "/blog"
repository               : "ontheline/otl-book"

# Social Sharing
twitter:
  username               : &twitter "doughertyjack"
facebook:
  username               : 
  app_id                 :
  publisher              :
og_image                 : "/assets/images/site-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/doughertyjack"


# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/jack.png"
  bio              : "Optional bio here."
  location         : "Hartford, CT"
  email            :
  uri              : # "https://mademistakes.com"
  home             : # "https://mademistakes.com"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : *facebook
  foursquare       :
  github           : "jackdougherty"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : #"mmistakes"
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : # https://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : *twitter
  vine             :
  weibo            :
  xing             :
  youtube          :



# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : # Replace this with your ID, or delete

# SEO Related
google_site_verification : # "UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y" # Replace this with your ID, or delete

# Search compilation (not yet working in GitHub Pages)
search                   : true # true, false (default)
search_full_content      : true # true, false (default)

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      share: true
      comments: false
      read_time: false
      sidebar:
        nav: "pages"
